spring:
  profiles:
    active: local
  mvc:
    locale: ko_KR
  messages:
    basename: classpath:/messages/message
    encoding: UTF-8

---
spring:
  profiles: local
server:
  port: 8000
config:
  restTemplate:
    timeout: 5000
    maxConnTotal: 100
    maxConnPerRoute: 50
  robot:
    serviceType: robot
    brokerip: 15.164.145.178
    brokerport: 4222
    restApiUrl: http://15.164.145.178:8080
  common:
    eventhub:
      connString: Endpoint=sb://yj-eventhub01.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=uPrHV6CYGzN3UzzU0Mfv/okVOH6FfY3q/qf/NXz+nq4=
      name: eventhub01

---
spring:
  profiles: dev
config:
  restTemplate:
    timeout: ${}
    maxConnTotal: ${}
    maxConnPerRoute: ${}
  robot:
    serviceType: ${}
    brokerip: ${}
    brokerport: ${}
    restApiUrl: ${}
  common:
    eventhub:
      connString: ${}
      name: ${}
