spring:
  profiles:
    active: loacl
  mvc:
    locale: ko_KR
  messages:
    basename: classpath:/messages/message
    encoding: UTF-8

---
spring:
  profiles: loacl
server:
  port: 8000
config:
  restTemplate:
    timeout: 5000
    maxConnTotal: 100
    maxConnPerRoute: 50
  robot:
    serviceType: robot
    brokerip: 15.164.145.178
    brokerport: 4222
    restApiUrl: http://15.164.145.178:8080
    tempRobotID: addy-id1
  common:
    eventhub:
      connString: Endpoint=sb://adt-dev-kc-uplink-tsop-evh.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=bcKVhcDjGNLiiQ401cV+5MFpmhMrNa3Yt6hHY7oSfwI=
      name: uplink-hub

---
spring:
  profiles: dev
config:
  restTemplate:
    timeout: ${APP_RESTTEMPLATE_TIMEOUT}
    maxConnTotal: ${APP_RESTTEMPLATE_MAX_CONN_TOTAL}
    maxConnPerRoute: ${APP_RESTTEMPLATE_MAX_CONN_PRE_ROUTE}
  robot:
    serviceType: ${APP_SERVICE_TYPE}
    brokerip: ${APP_ROBOT_BROKER_IP}
    brokerport: ${APP_ROBOT_BROKER_PORT}
    restApiUrl: ${APP_ROBOT_SERVER_ADDRESS}
    tempRobotID: ${APP_ROBOT_ID}
  common:
    eventhub:
      connString: ${APP_EVENT_HUBE_CONN_STRING}
      name: ${APP_EVENT_HUB_NAME}